### ISSUE TITLE
Add support for --project Fossa CLI option

### ISSUE THREAD

**Issue by aitoracedo** [fossas/fossa-action#17]
In the Fossa web interface the Title column has a fixed width so it would be very useful to add the --project CLI flag to the GitHub action

**Comment by rolodato** [comment]
Apologies for the delay here! While not a direct answer to your request, it is possible to set almost all CLI options including `project` and `title` from a `.fossa.yml` configuration file: https://github.com/fossas/fossa-cli/blob/ad4ab0b369995c7fc6d6056d0038141c492ad8cb/docs/references/files/fossa-yml.md.

This should let you work around the limitation while we work on improvements to this action.
