### ISSUE TITLE
Update v1 tag to point to v1.1.0

### ISSUE THREAD

**Issue by 3flex** [fossas/fossa-action#20]
The convention for GitHub Actions is to have a major version tag updated when a new point release is made. The `v1` tag in this repo should therefore reference the same commit as the `v1.1.0` tag, and be updated again when a new version is released.

Thanks for your consideration!

**Comment by TWiStErRob** [comment]
Please push the the v1 tag to the latest released, without that, Dependabot, Renovatebot, and GitHub Action users will never see the newer versions.

**Comment by TWiStErRob** [comment]
cc @rolodato @himynameisdave

**Comment by rolodato** [comment]
Apologies for the delay here - the `v1` tag now points to the same revision as the `v1.3.1` release. Thanks for pointing it out!
