### ISSUE TITLE
Return differ exit code when "No analysis targets found" error

### ISSUE THREAD

**Issue by helobinvn** [fossas/fossa-action#34]
### UC
We would like to enable `fossa analyze` by default for all our projects, and the scan will be enforced from the organization level, however, some repos will actually not contain any dependency (ansible/ terraform/yaml stuff) or use programming languages that are not supported by Fossa yet. Therefore, the fossa scan on these repos will end up with `No analysis targets found` and its return code is the same as other errors. We would like the distinguish this kind of error and mark it as `success` instead.

### E.g error log
```
[ERROR] ----------
  An issue occurred

  >>> Relevant errors

    Error

      No analysis targets found in directory.

      Make sure your project is supported. See the user guide for details:
          https://github.com/fossas/fossa-cli/blob/v3.4.9/docs/README.md


      Traceback:
        - fossa-analyze


➜  echo $?
1
```

Please help to check this use case and thanks for your consideration!

**Comment by csasarak** [comment]
I apologize for the delay on answering this. We actually just recently changed the FOSSA CLI that powers this action to have this behavior in the [latest release](https://github.com/fossas/fossa-cli/releases/tag/v3.9.0). The action should now inherit that behavior.
