### ISSUE TITLE
Question: Is this Action still in development and/or is it still supported?

### ISSUE THREAD

**Issue by gab-arrobo** [fossas/fossa-action#35]
Does this Action work with repositories that are part of organizations? or does it only work with personal repositories>

Thank you!

**Comment by csasarak** [comment]
This action is still supported and developed by FOSSA and there shouldn't be any obstacle to running it whether or not the repo is part of an organization or someone's personal account. Are you having any specific troubles getting it to run?

**Comment by gab-arrobo** [comment]
Hi @csasarak, thanks for your reply. Yes, we are facing issue trying to use this action for repos that are part of an organization. For example, the FOSSA action fails in this PR (https://github.com/omec-project/metricfunc/actions/runs/7804093655/job/21285319095?pr=27) indicating that `Input required and not supplied: api-key`. However, this same action when used in my personal fork of the same repo successfully completes (https://github.com/gab-arrobo/metricfunc/actions/runs/7779791286/job/21211496635). Do you have any suggestion on how to address this isue?

**Comment by csasarak** [comment]
I suspect that there is an issue with how you've [configured your secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#about-secrets) and when the action tries to insert your api key it is just inserting the empty string which then manifests as an exception thrown from the part of the action which tries to use the secret. 

Notice the differences in the values in the "Setup Job" step in the workflow log between your personal account and the organization account. Additionally, the action run in the organization repo lists "None" as its source of secrets while the one in your personal account lists "Actions". I would check the repository's configuration and make sure that it has access to the necessary secrets.

**Comment by gab-arrobo** [comment]
Thanks for your input!
