### ISSUE TITLE
Update to Node.js 20 to Address GHA Deprecation Warning

### ISSUE THREAD

**Issue by peters** [fossas/fossa-action#36]
We've recently encountered a deprecation warning in our GitHub Actions (GHA) workflows related to the version of Node.js fossa are currently using. To ensure our CI/CD processes remain efficient and up-to-date, fossa needs to update their Node.js version to 20.

![image](https://github.com/fossas/fossa-action/assets/869/0bec95ea-76ae-4e1f-8077-7217a5e83384)

**Comment by csasarak** [comment]
Hi @peters, thanks for filing this issue. I've made a PR for this. Once we make a new release with the changes this should be fixed for you.

**Comment by peters** [comment]
Thanks for the fast response! The warning is now gone🥳
