### ISSUE TITLE
Option to use FOSSA CLI V1

### ISSUE THREAD

**Issue by lucacome** [fossas/fossa-action#8]
I'm having a couple of issues with V2, https://github.com/fossas/spectrometer/issues/227 and https://github.com/fossas/spectrometer/issues/152 mostly because it looks like it's not very tunable or mature.

Is there a way that this action can have an option to use V1? Or am I better off using https://github.com/fossa-contrib/fossa-action (that I think it's not officially from Fossa)?

**Comment by Serubin** [comment]
@lucacome V1 of FOSSA CLI is deprecated and we have no planned work to incorporate support for it into this github action. However, this is a user-contributed github action based on V1 that you can try if needed. 

https://github.com/marketplace/actions/fossa-action

**Comment by lucacome** [comment]
Thanks @Serubin looks like this action is working well now (one of the two issues was addressed) and I forgot to close this issue!
